/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsResult {
  'totalClasses' : bigint,
  'studentStats' : Array<StudentStat>,
  'totalStudents' : bigint,
  'overallRate' : number,
  'classStats' : Array<ClassStat>,
}
export type AttendanceId = bigint;
export interface AttendanceRecord {
  'id' : AttendanceId,
  'dateKey' : string,
  'studentId' : StudentId,
  'source' : string,
  'classId' : ClassId,
  'timestamp' : Time,
  'confidence' : number,
}
export interface Class {
  'id' : ClassId,
  'name' : string,
  'teacher' : TeacherId,
  'studentIds' : Array<StudentId>,
}
export type ClassId = bigint;
export interface ClassStat {
  'rate' : number,
  'classId' : ClassId,
  'presentCount' : bigint,
  'className' : string,
  'enrolledCount' : bigint,
}
export interface Profile {
  'id' : Principal,
  'name' : string,
  'role' : Role,
  'faceImageUrl' : string,
}
export type Role = { 'teacher' : null } |
  { 'student' : null };
export type StudentId = Principal;
export interface StudentStat {
  'studentId' : StudentId,
  'studentName' : string,
  'rate' : number,
  'presentCount' : bigint,
  'totalSessions' : bigint,
}
export type TeacherId = Principal;
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClass' : ActorMethod<[string], ClassId>,
  'getAnalytics' : ActorMethod<
    [[] | [ClassId], [] | [string], [] | [string]],
    AnalyticsResult
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClassAttendance' : ActorMethod<
    [ClassId, string],
    Array<AttendanceRecord>
  >,
  'getMyAttendance' : ActorMethod<[], Array<AttendanceRecord>>,
  'getMyProfile' : ActorMethod<[], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinClass' : ActorMethod<[ClassId], boolean>,
  'listClassStudents' : ActorMethod<[ClassId], Array<StudentId>>,
  'listClasses' : ActorMethod<[], Array<Class>>,
  'listStudents' : ActorMethod<[], Array<Profile>>,
  'markAttendance' : ActorMethod<
    [ClassId, Principal, number],
    [] | [AttendanceId]
  >,
  'markMyAttendanceQR' : ActorMethod<[ClassId], [] | [AttendanceId]>,
  'saveProfile' : ActorMethod<[string, Role, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];