/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClassId = IDL.Nat;
export const StudentId = IDL.Principal;
export const StudentStat = IDL.Record({
  'studentId' : StudentId,
  'studentName' : IDL.Text,
  'rate' : IDL.Float64,
  'presentCount' : IDL.Nat,
  'totalSessions' : IDL.Nat,
});
export const ClassStat = IDL.Record({
  'rate' : IDL.Float64,
  'classId' : ClassId,
  'presentCount' : IDL.Nat,
  'className' : IDL.Text,
  'enrolledCount' : IDL.Nat,
});
export const AnalyticsResult = IDL.Record({
  'totalClasses' : IDL.Nat,
  'studentStats' : IDL.Vec(StudentStat),
  'totalStudents' : IDL.Nat,
  'overallRate' : IDL.Float64,
  'classStats' : IDL.Vec(ClassStat),
});
export const AttendanceId = IDL.Nat;
export const Time = IDL.Int;
export const AttendanceRecord = IDL.Record({
  'id' : AttendanceId,
  'dateKey' : IDL.Text,
  'studentId' : StudentId,
  'source' : IDL.Text,
  'classId' : ClassId,
  'timestamp' : Time,
  'confidence' : IDL.Float64,
});
export const Role = IDL.Variant({ 'teacher' : IDL.Null, 'student' : IDL.Null });
export const Profile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'role' : Role,
  'faceImageUrl' : IDL.Text,
});
export const TeacherId = IDL.Principal;
export const Class = IDL.Record({
  'id' : ClassId,
  'name' : IDL.Text,
  'teacher' : TeacherId,
  'studentIds' : IDL.Vec(StudentId),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClass' : IDL.Func([IDL.Text], [ClassId], []),
  'getAnalytics' : IDL.Func(
      [IDL.Opt(ClassId), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [AnalyticsResult],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClassAttendance' : IDL.Func(
      [ClassId, IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getMyAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinClass' : IDL.Func([ClassId], [IDL.Bool], []),
  'listClassStudents' : IDL.Func([ClassId], [IDL.Vec(StudentId)], ['query']),
  'listClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
  'listStudents' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'markAttendance' : IDL.Func(
      [ClassId, IDL.Principal, IDL.Float64],
      [IDL.Opt(AttendanceId)],
      [],
    ),
  'markMyAttendanceQR' : IDL.Func([ClassId], [IDL.Opt(AttendanceId)], []),
  'saveProfile' : IDL.Func([IDL.Text, Role, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClassId = IDL.Nat;
  const StudentId = IDL.Principal;
  const StudentStat = IDL.Record({
    'studentId' : StudentId,
    'studentName' : IDL.Text,
    'rate' : IDL.Float64,
    'presentCount' : IDL.Nat,
    'totalSessions' : IDL.Nat,
  });
  const ClassStat = IDL.Record({
    'rate' : IDL.Float64,
    'classId' : ClassId,
    'presentCount' : IDL.Nat,
    'className' : IDL.Text,
    'enrolledCount' : IDL.Nat,
  });
  const AnalyticsResult = IDL.Record({
    'totalClasses' : IDL.Nat,
    'studentStats' : IDL.Vec(StudentStat),
    'totalStudents' : IDL.Nat,
    'overallRate' : IDL.Float64,
    'classStats' : IDL.Vec(ClassStat),
  });
  const AttendanceId = IDL.Nat;
  const Time = IDL.Int;
  const AttendanceRecord = IDL.Record({
    'id' : AttendanceId,
    'dateKey' : IDL.Text,
    'studentId' : StudentId,
    'source' : IDL.Text,
    'classId' : ClassId,
    'timestamp' : Time,
    'confidence' : IDL.Float64,
  });
  const Role = IDL.Variant({ 'teacher' : IDL.Null, 'student' : IDL.Null });
  const Profile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'role' : Role,
    'faceImageUrl' : IDL.Text,
  });
  const TeacherId = IDL.Principal;
  const Class = IDL.Record({
    'id' : ClassId,
    'name' : IDL.Text,
    'teacher' : TeacherId,
    'studentIds' : IDL.Vec(StudentId),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClass' : IDL.Func([IDL.Text], [ClassId], []),
    'getAnalytics' : IDL.Func(
        [IDL.Opt(ClassId), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [AnalyticsResult],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClassAttendance' : IDL.Func(
        [ClassId, IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getMyAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinClass' : IDL.Func([ClassId], [IDL.Bool], []),
    'listClassStudents' : IDL.Func([ClassId], [IDL.Vec(StudentId)], ['query']),
    'listClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
    'listStudents' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'markAttendance' : IDL.Func(
        [ClassId, IDL.Principal, IDL.Float64],
        [IDL.Opt(AttendanceId)],
        [],
      ),
    'markMyAttendanceQR' : IDL.Func([ClassId], [IDL.Opt(AttendanceId)], []),
    'saveProfile' : IDL.Func([IDL.Text, Role, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };